# sudo usermod -a -G sudo gitlab-runner
# sudo visudo or sudo vi /etc/sudoers
# %gitlab-runner ALL=(ALL) NOPASSWD: ALL

stages:
    - qa-tools
    - dependencies
    - data-distribution-service
    - feature-test
    - target-package
    - target-install
    - deploy
    - target-clean

.agent-47: &agent-47
#    retry: 1
    tags:
        - agent-smith

.only_stable: &only_stable
    only:
        - master
        - /^release-.*$/

.tumbleweed: &tumbleweed
    only:
        - develop

.parent-cache: &parent-cache
    key: "Ubuntu-18-10-DDS-Dev-Tools" # ${CI_COMMIT_REF_SLUG}
    paths:
        - ${DEPS_INSTALL_DIR}/

.artifacts-folder: &artifacts-folder
    artifacts:
        name: "${CI_JOB_NAME}_${CI_COMIT_REF_NAME}_${CI_COMMIT_SHA}"
        when: always
        expire_in: 31d
        paths:
            - ${DEPS_INSTALL_DIR}

.push-cache: &push-cache
    cache:
    <<: *parent-cache
    policy: push

.pull-cache: &pull-cache
    cache:
    <<: *parent-cache
    policy: pull

.build-metadata: &build-metadata
    <<: *agent-47
    <<: *pull-cache
    stage: test

variables:
    # DEPS_INSTALL_DIR: /opt/devslibs
    # DEPS_INSTALL_DIR: ${CI_PROJECT_DIR}/devslibs
    DEPS_INSTALL_DIR: ${HOME}/devslibs

before_script:
    - cmake --version
    - make --version
    - date
    - hostname

after_script:
    - date

uncrustify:
    <<: *agent-47
    stage: qa-tools

    before_script:
        - date -u

    script:
        - cmake --version
        - git clone --depth=1 https://github.com/uncrustify/uncrustify.git
        - cd uncrustify
        - cmake -E make_directory build
        - cmake -E chdir build cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_INSTALL_DIR} 
        - cmake --build build --target all --clean-first 
        - cmake --build build --target install
        - cd ..

    after_script:
        - date -u


cppcheck:
    <<: *agent-47
    stage: qa-tools

    before_script:
        - date -u

    script:
        - cmake --version
        - git clone --depth=1 https://github.com/danmar/cppcheck.git
        - cd cppcheck
        - cmake -E make_directory build
        - cmake -E chdir build cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_INSTALL_DIR}
        - cmake --build build --target all --clean-first 
        - cmake --build build --target install
        - cp --recursive --verbose cfg  ${DEPS_INSTALL_DIR}/bin || true
        - cd ..

    after_script:
        - date -u

doxygen:
    <<: *dedicated-runner 
    stage: primal-dependencies

    before_script:
        - date -u

    script:
        - cmake --version
        - git clone --depth=1 https://github.com/doxygen/doxygen.git 
        - cd doxygen
        - cmake -E make_directory build
        - cmake -E chdir build cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_INSTALL_DIR}
        - cmake --build build --target all --clean-first
        - cmake --build build --target install
        - cd ..

    after_script:
        - date -u
