stages:
    - dependencies
    - compile
    - test
    - target-package
    - target-install
    - deploy
    - target-clean

.dedicated-runner: &dedicated-runner
    retry: 1
    tags:
        - agent-smith

.default-cache: &default-cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/ruby

before_script:
    - date
    - cmake --version
    - make --version

after_script:
    - date


variables:
    DEPS_INSTALL_DIR: /home/gitlab-runner/builds/$CI_PROJECT_NAME
#    DEPS_INSTALL_DIR: /home/gitlab-runner/$CI_COMMIT_REF_NAME

# Cache in between builds
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - ${DEPS_INSTALL_DIR}

uncrustify:
    <<: *dedicated-runner 
    stage: dependencies

    before_script:
        - date -u

    script:
        - cmake --version
        - git clone --depth=1 https://github.com/uncrustify/uncrustify.git
        - cd uncrustify
        - cmake -E make_directory build
        - cmake -E chdir build cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_INSTALL_DIR}/devslibs
        - cmake --build build --target all --clean-first 
        - cmake --build build --target install
        - cd ..

    after_script:
        - date -u

