
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    message(STATUS "Setting build type to 'Debug' as none was specified.")
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Choose the type of build." FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo" "Coverage" "Profiling")

endif()

cmake_host_system_information(RESULT HOST_LOGICAL_CORE_NO QUERY NUMBER_OF_LOGICAL_CORES)
cmake_host_system_information(RESULT HOST_PHYSICAL_CORE_NO QUERY NUMBER_OF_PHYSICAL_CORES)
cmake_host_system_information(RESULT HOST_PHYSICAL_MEMORY QUERY TOTAL_PHYSICAL_MEMORY)


set(AOL "${CMAKE_SYSTEM_PROCESSOR}-${CMAKE_HOST_SYSTEM_NAME}-${CMAKE_CXX_COMPILER_ID}_GCC_${CMAKE_CXX_COMPILER_VERSION}")
#set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_COLOR_MAKEFILE ON)
set(CMAKE_RULE_MESSAGES ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_INCLUDE_DIRECTORIES_PROJECT_BEFORE ON)
set(CMAKE_INCLUDE_CURRENT_DIR_IN_INTERFACE ON)
#set(CMAKE_LINK_DEPENDS_NO_SHARED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(BUILD_SHARED_LIBS)
    set(CMAKE_DEBUG_POSTFIX             "${STATIC_POSTFIX}.d"   CACHE STRING "Set Debug library postfix" FORCE)
    set(CMAKE_RELEASE_POSTFIX           "${STATIC_POSTFIX}"     CACHE STRING "Set Release library postfix" FORCE)
    set(CMAKE_MINSIZEREL_POSTFIX        "${STATIC_POSTFIX}"     CACHE STRING "Set MinSizeRel library postfix" FORCE)
    set(CMAKE_RELWITHDEBINFO_POSTFIX    "${STATIC_POSTFIX}"     CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
    set(CMAKE_FIND_LIBRARY_SUFFIXES     "${STATIC_POSTFIX}.so"  CACHE STRING "Set find library suffix" FORCE)
    set(CMAKE_FIND_LIBRARY_PREFIXES     "${STATIC_POSTFIX}lib"  CACHE STRING "Set find library prefix" FORCE)
else(BUILD_SHARED_LIBS)
    set(CMAKE_DEBUG_POSTFIX             ".d"         CACHE STRING "Set Debug library postfix" FORCE)
    set(CMAKE_RELEASE_POSTFIX           ""           CACHE STRING "Set Release library postfix" FORCE)
    set(CMAKE_MINSIZEREL_POSTFIX        ""           CACHE STRING "Set MinSizeRel library postfix" FORCE)
    set(CMAKE_RELWITHDEBINFO_POSTFIX    ".r.d"       CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
    set(CMAKE_COVERAGE_POSTFIX          ".cov"       CACHE STRING "Set Coverage library postfix" FORCE)
    set(CMAKE_COVERAGE_POSTFIX          ".prof"      CACHE STRING "Set profile library postfix" FORCE)
    set(CMAKE_FIND_LIBRARY_SUFFIXES     ".a"         CACHE STRING "Set find library suffixe" FORCE)
    set(CMAKE_FIND_LIBRARY_PREFIXES     "lib"        CACHE STRING  "Set find library prefix" FORCE)
endif(BUILD_SHARED_LIBS)

# set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;Coverage;Profiling")
set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/${AOL}-${CMAKE_BUILD_TYPE})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_INSTALL_PREFIX}/lib CACHE PATH "Output directory for static libraries")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_INSTALL_PREFIX}/lib CACHE PATH "Output directory for shared libraries")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_INSTALL_PREFIX}/bin CACHE PATH "Output directory for runtime binaries")

include(GNUInstallDirs)
set(CMAKE_INSTALL_SYSCONFDIR "${CMAKE_INSTALL_PREFIX}/etc")
set(CMAKE_INSTALL_INCLUDEDIR "${CMAKE_INSTALL_PREFIX}/include")
set(CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_PREFIX}/lib")
set(CMAKE_INSTALL_BINDIR "${CMAKE_INSTALL_PREFIX}/bin")
